name: foodivoire
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  country_code_picker: ^3.0.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_staggered_grid_view: ^0.4.0
  geolocator: ^10.1.0
  get_it: ^7.6.4
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  location: ^5.0.3
  provider: ^5.0.0
  readmore: ^2.2.0
  share_plus: ^7.2.1
  shared_preferences: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: font\Inter-VariableFont_slnt,wght.ttf
