name: foodivoire
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  readmore: ^2.2.0
  country_code_picker: ^3.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.7
  flutter_staggered_grid_view: ^0.4.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
  fonts:
    - family: Inter
      fonts:
        - asset: font\Inter-VariableFont_slnt,wght.ttf

